version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # gRPC port
      - "6334:6334" # REST API port (optional, but good to expose)
    volumes:
      - ./qdrant_storage:/qdrant/storage # Persist Qdrant data
    # You might want to add healthcheck or other configurations later